### PR TITLE
Try fix AppName not work for Tradionnal Chinese on iOS

### PR DESCRIPTION
**Pull request by SyaoranChang**
Hi,

I think this should be easier to use for both Android and iOS platforms, about "-r" or "-" issue, like  Unrecognized Locale #3 
And Android doesn't work with "zh-Hant" and "zh-Hans", but iOS does.

Try fix AppName not work for Tradionnal Chinese on iOS
Add ReplaceLanguageCode() Replace LanguageCode from "-r" to "-" for iOS LanguageCode use "zh-Hant" and "zh-Hans" for Chinese for iOS

### CODE REVIEW

**Comment by yasirkula** [comment]
Hi,

GitHub shows the whole file as changed. Could you fix it with another commit? And did you try [zh-CN and zh-TW](https://github.com/yasirkula/UnityMobileLocalizedAppTitle/issues/3#issuecomment-1858938316) beforehand?

**Comment by SyaoranChang** [comment]
> Hi,
> 
> GitHub shows the whole file as changed. Could you fix it with another commit? And did you try [zh-CN and zh-TW](https://github.com/yasirkula/UnityMobileLocalizedAppTitle/issues/3#issuecomment-1858938316) beforehand?

1.OK, I will create a new Pull Request later
2.I only try zh and zh-rTW for Chinese, I didn't try zh-CN and zh-TW beforehand.

**Comment by yasirkula** [comment]
Did `zh` not work? And could you give zh-TW a try? If it works on your device, as well, then it should be a solid solution.

**Comment by SyaoranChang** [comment]
Hi,

Sorry for taking so long to respond, I just had time to do the test today.
I tested zh-CN and zh-TW using the simulator on Android 7, 9 and iOS 15 and the language change seems to be correct!
It looks like my changes were not needed.
Thank you for your reply.

**Comment by SyaoranChang** [comment]
This is the article I first read.
But it doesn't seem to be necessary anymore.
https://stackoverflow.com/questions/44714408/android-simplified-chinese-and-traditional-chinese-not-working

**Comment by yasirkula** [comment]
Glad to hear it! Thank you for sharing your findings.

**Pull request closed without merging**
