### PR TITLE
Support not change PlayerSettings.productName

### PR DESCRIPTION
**Pull request by kavenGw**

### CODE REVIEW

**Comment by yasirkula** [comment]
You can just disable "Localize App Name on Android" and "Localize App Name on iOS" toggles.

**Comment by kavenGw** [comment]
> You can just disable "Localize App Name on Android" and "Localize App Name on iOS" toggles.
Hi, I have a game in which the product name is Block and the app name is Strangeblock, this plugin works great except change my product name to Strangeblock after I build, and it will take some problems. I think the product name is not needed as the same as the app name.

**Comment by yasirkula** [comment]
Hi, I don't know the difference between app name and product name. I normally change Product Name to change my app's name (if I am not using localization). Can you tell me the difference and which issues you're encountering when this plugin modifies productName?

**Comment by kavenGw** [comment]
Hi, As I know, the product name is the default app name in all languages, and the default Identify of the product is com.companyname.productname.

After using your localization plugin, we can use different app names in different languages. 
 
In my situation, I created a product named Block years ago, But when the product is going to online, we decided to use the name StrangeBlock as the app name, also StrangeBlockxxx in some specific regions, and a new version StrangeBlockMarathon is in developing, and all of them use the same unity product.

We also have some build script which use the application.productname, so we don't want to change the product name. Just use your plugin to change the AppName after building.

**Comment by yasirkula** [comment]
Were you able to test the change on iOS as well? I'd like to know if Application.productName is also redundant there before making this change.

**Comment by kavenGw** [comment]
Hi，I have checked on iOS that the en.proj generates successes with the right name. 

I also changed the GenerateAndroidResources function to Public because I had a MenuItem which will change the localized name between my 2 games, so I need to generate the Android aar file after I click the menuitem.

**Comment by yasirkula** [comment]
Can you verify that in addition to generating en.proj correctly, it behaves correctly on the phone, as well? For example, try setting default language to EN and its title to Test EN. For French, set the title to Test FR. Now, when you switch your phone's language to French, it should show Test FR. For English, Test EN. For Arabic, Test EN. For Turkish, Test EN, etc.

**Comment by kavenGw** [comment]
Sure, my APP does not support FR yet, but I tested KR and ZH, they works greate.

**Comment by yasirkula** [comment]
I've made a commit to rename the variable and show it only while Alt/Option key is held since it's a special variable that shouldn't clutter the user interface by default. In your project, you should set it to false once again since its name has changed.

**Pull request merged**
